name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Tests
      run: mvn -B test --file pom.xml

    - name: Publish Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports/

    - name: Archive Build
      uses: actions/upload-artifact@v2
      with:
        name: java-app
        path: target/*.jar
